languageCode:           "ko"
title:                  "Bootstrap Icons"
baseURL:                "https://icons.getbootstrap.kr"
enableInlineShortcodes: true
enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false

module:
  mounts:
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/assets/img/favicons/favicon.ico
      target:           static/favicon.ico
    - source:           bootstrap-icons.svg
      target:           static/bootstrap-icons.svg
    - source:           icons
      target:           static/assets/icons
    - source:           font
      target:           static/font

params:
  description:          "Bootstrap용 오픈 소스 SVG 아이콘 라이브러리"
  social_image_path:    /assets/img/bootstrap-icons-social.png

  version:              "1.4.0"
  bs_docs_version:      "5.0"

  main:                 "https://getbootstrap.kr"
  github_org:           "https://github.com/twbs"
  repo:                 "https://github.com/twbs/icons"
  twitter:              "getbootstrap"
  slack:                "https://bootstrap-slack.herokuapp.com"
  blog:                 "https://blog.getbootstrap.com"
  expo:                 "https://expo.getbootstrap.com"
  themes:               "https://themes.getbootstrap.com"
  opencollective:       "https://opencollective.com/bootstrap"
